config/routes.rb
Rails.application.routes.draw do
  get 'homes/about'
  get 'writers/edit'
  get 'writers/show'
  devise_for :writers, controllers: {
  	registrations: 'writers/registrations',
  	sessions: "writers/sessions"
  }

  devise_scope :writer do
  	get 'login' => 'writers/sessions#new'
  	post 'login' => 'writers/sessions#create'
  end

  root 'articles#index'
  resources :articles, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :writers, only: [:show, :edit, :update]

  get 'about' => 'homes#about'

  get 'writers/edit_password/:id' => 'writers#edit_password', as: 'edit_password'
  patch 'writers/update_password/:id' => 'writers#update_password', as: 'update_password'
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :writer

  attachment :image

  validates :title, presence: true, length: { maximum: 100 }
  validates :body, presence: true
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :guard_other, only: [:new, :edit]

  def new
  	@article = Article.new
  end

  def create
  	@article = Article.new(article_params)
  	@article.writer_id = current_writer.id
  	if @article.save
  	  redirect_to article_path(@article)
  	else
  	  redirect_back(fallback_location: root_url)
  	end
  end

  def index
  	# @articles = Article.page(params[:page]).reverse_order
    @q = Article.search(params[:q])
    @articles = @q.result(distinct: true).page(params[:page]).reverse_order
  end

  def show
  	@article = Article.find(params[:id])
    @articles = Article.all.order(created_at: :desc).limit(4)
    @writer = Writer.find(1)
  end

  def edit
  	@article = Article.find(params[:id])
  end

  def update
  	@article = Article.find(params[:id])
  	if @article.update(article_params)
  	  redirect_to article_path(@article)
  	else
  	  redirect_back(fallback_location: root_url)
  	end
  end

  def destroy
  	@article = Article.find(params[:id])
  	if @article.destroy
  	  redirect_to root_path
  	else
  	  redirect_back(fallback_location: root_url)
  	end
  end

  private

  def article_params
  	params.require(:article).permit(:title, :body, :image)
  end

  def guard_other
  	unless writer_signed_in?
  	  redirect_to root_path
  	end
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_index.html.erb
<% @articles.each do |article| %>
  <div class="index_item">
    <%= link_to article_path(article) do %>
      <div class="date_index">
        <%= article.created_at.strftime("%Y-%m-%d %H:%M") %>
      </div>

      <div class="title_index">
        <%= article.title %>
      </div>
      <%= attachment_image_tag article, :image, :fill, 90, 50, format: 'jpeg', class: 'image center-block' %>
    <% end %>
  </div>
<% end %>

app/views/articles/_paginate.html.erb
<div class="index">
  <%= render 'index' %>
</div>

<div class="paginate">
　<%= paginate articles %>
</div>

app/views/articles/edit.html.erb
<%= link_to article_path(@article) do %>
    <div class="back"></div>
<% end %>

<h1 class="h1">Edit -Article-</h1>

<%= form_with model: @article, url: article_path(@article), local: true do |f| %>
  <div class="form-group">
    <%= f.text_field :title, placeholder: 'Title (max:100)', class: 'form-control' %>
  </div>

  <div class="">
  	<%= attachment_image_tag @article, :image, :fill, 100, 50, format: 'jpeg' %>
    <%= f.attachment_field :image, class: 'image_' %>
  </div>
  
  <div class="form-group">
    <%= f.text_area :body, placeholder: 'How was your day?', rows: 50, class: 'form-control' %>
  </div>

  <%= f.submit 'Update', class: 'btn btn-warning pull-right' %>
<% end %>

app/views/articles/index.html.erb
<% unless writer_signed_in? %>
  <div class="about_background_image">
    <h1 class="text-center myBlog">MY BLOG</h1>
  </div>
<% end %>

<h1 class="h1">Articles</h1>
<!-- <div class="row">
  <p class="col-md-11 text-right">(<%= @articles.count %> articles)</p>
</div> -->

<%= search_form_for @q, url: root_path do |f| %>

  <div class="pull-right">
    <%= f.search_field :title_or_body_cont, placeholder: 'Keyword', class: 'form-group' %>
    <%= f.submit 'Search', class: 'btn btn-warning btn-xs search' %>
  </div>
<% end %>

<%= render 'paginate', articles: @articles %>

app/views/articles/new.html.erb
<%= link_to root_path, data: { 'turbolinks' => false } do %>
  <div class="back"></div>
<% end %>

<h1 class="h1">Create New Article</h1>

<%= form_with model: @article, url: articles_path, local: true do |f| %>

<div class="form-group">
  <%= f.text_field :title, placeholder: 'Title (max:100)', class: 'form-control' %>
</div>

<div class="">
  <%= f.attachment_field :image, class: 'image_' %>
</div>

<div class="form-group">
  <%= f.text_area :body, placeholder: 'How was your day?',rows: 50, class: 'form-control' %>
</div>

  <%= f.submit 'Create', class: 'btn btn-warning pull-right' %>
<% end %>

app/views/articles/show.html.erb
<%= link_to root_path, data: { 'turbolinks' => false } do %>
  <div class="back"></div>
<% end %>

<% if @article.writer == current_writer %>
  <%= link_to edit_article_path(@article) do %>
    <div class="articles_edit pull-right"></div>
  <% end %>

  <%= link_to article_path(@article), method: :delete, data: { confirm: '本当に削除しますか？' } do %>
    <div class="delete pull-right"></div><br>
  <% end %>
<% end %>

<h1 class="title"><%= @article.title %></h1>

<%= attachment_image_tag @writer, :image, :fill, 50, 50, format: 'jpeg', class: 'image_writer pull-right' %>
<p class="article_show_name pull-right">
	WRITER: <%= @article.writer.name %>
</p>

<div class="body">
  <%= attachment_image_tag @article, :image, :fill, 400, 250, format: 'jpeg', class: 'image' %>
  <%= markdown(@article.body).html_safe %>
</div>

<div class="index">
  <%= render 'index' %>
</div>