config/routes.rb
Rails.application.routes.draw do
  get 'homes/about'
  get 'writers/edit'
  get 'writers/show'
  devise_for :writers, controllers: {
  	registrations: 'writers/registrations',
  	sessions: "writers/sessions"
  }

  devise_scope :writer do
  	get 'login' => 'writers/sessions#new'
  	post 'login' => 'writers/sessions#create'
  end

  root 'articles#index'
  resources :articles, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :writers, only: [:show, :edit, :update]

  get 'about' => 'homes#about'

  get 'writers/edit_password/:id' => 'writers#edit_password', as: 'edit_password'
  patch 'writers/update_password/:id' => 'writers#update_password', as: 'update_password'
end

app/models/writer.rb
class Writer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable

  has_many :articles, dependent: :destroy

  validates :name, length: { maximum: 30 }
  validates :introduction, length: { maximum: 200 }

  attachment :image
end

app/controllers/writers/confirmations_controller.rb
# frozen_string_literal: true

class Writers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/writers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Writers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/writers/passwords_controller.rb
# frozen_string_literal: true

class Writers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/writers/registrations_controller.rb
# frozen_string_literal: true

class Writers::RegistrationsController < Devise::RegistrationsController
  before_action :guard_signup, only: [:create, :new, :cancel, :destroy]
  # before_action :configure_account_update_params, only: [:update]

  private

  def guard_signup
    raise ActionController::RoutingError, 'NOT FOUND'
  end
  
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/writers/sessions_controller.rb
# frozen_string_literal: true

class Writers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/writers/unlocks_controller.rb
# frozen_string_literal: true

class Writers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/writers_controller.rb
class WritersController < ApplicationController
  before_action :guard_other

  def show
  	@writer = Writer.find(params[:id])
  end

  def edit
  	@writer = Writer.find(params[:id])
  end

  def update
  	@writer = Writer.find(params[:id])
  	if @writer.update(writer_params)
  	  redirect_to writer_path(@writer)
  	else
  	  redirect_back(fallback_location: root_url)
  	end
  end

  def edit_password
    @writer = Writer.find(params[:id])
  end

  def update_password
    @writer = Writer.find(params[:id])
    if @writer.update(writer_params)
      redirect_to root_path
    else
      render :edit_password
    end
  end

  private

  def writer_params
  	params.require(:writer).permit(:name, :email, :introduction, :image, :password, :password_confirmation)
  end

  def guard_other
  	unless writer_signed_in?
  	  redirect_to root_path
  	end
  end
end

app/helpers/writers_helper.rb
module WritersHelper
end

app/views/writers/edit.html.erb
<%= link_to writer_path(@writer) do %>
  <div class="back"></div>
<% end %>

<h1 class="h1">Edit -Writer-</h1>

<%= form_with model: @writer, url: writer_path(@writer) do |f| %>
  
  <div class="row">
    <div class="form-group col-md-4">
      <%= f.text_field :name, placeholder: 'Name (max:30)', class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.email_field :email, placeholder: 'Email', class: 'form-control' %>
    </div>
  </div>

  <%= f.attachment_field :image, class: 'image_' %>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.text_area :introduction, rows: 15, placeholder: 'Introduction (max:200)', class: 'form-control' %>
    </div>
  </div>

  <%= f.submit 'Update', class: 'btn btn-warning' %>
<% end %>

<div class="change_password">
  <%= link_to 'Change Your Password', edit_password_path(@writer), class: 'btn btn-info' %>
</div>

app/views/writers/edit_password.html.erb
<%= link_to edit_writer_path(@writer), data: { 'turbolinks' => false } do %>
    <div class="back"></div>
<% end %>

<h1 class="h1">Change
Your Password</h1>

<%= form_with(model:@writer, url: update_password_path(@writer), method: :PATCH, local: true) do |f| %>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.password_field :password, placeholder: 'New password', class: 'form-control' %>
    </div>
  </div>

  <div class="row">
    <div class="form-group col-md-4">
      <%= f.password_field :password_confirmation, placeholder: 'Confirmation password', class: 'form-control' %>
    </div>
  </div>

  <%= f.submit 'Update', class: 'btn btn-info' %>
<% end %>

app/views/writers/show.html.erb
<div class="writers_show">
  <%= link_to root_path, data: { 'turbolinks' => false } do %>
    <div class="back"></div>
  <% end %>

  <h1 class="h1">My Page</h1>

  <%= attachment_image_tag @writer, :image, :fill, 60, 60, format: 'jpeg', class: 'image_writer' %>

  <%= link_to edit_writer_path(@writer) do %>
    <div class="writer_edit pull-right"></div>
  <% end %>

  <div class="name_writer">
    Name: <%= @writer.name %>
  </div>

  <div class="email_writer">
    Email: <%= @writer.email %>
  </div>

  <div class="intro_writer">
    <%= markdown(@writer.introduction).html_safe %>
  </div>
</div>