config/routes.rb
Rails.application.routes.draw do
  get 'homes/about'
  get 'writers/edit'
  get 'writers/show'
  devise_for :writers, controllers: {
  	registrations: 'writers/registrations',
  	sessions: "writers/sessions"
  }

  devise_scope :writer do
  	get 'login' => 'writers/sessions#new'
  	post 'login' => 'writers/sessions#create'
  end

  root 'articles#index'
  resources :articles, only: [:new, :show, :edit, :create, :update, :destroy]
  resources :writers, only: [:show, :edit, :update]

  get 'about' => 'homes#about'

  get 'writers/edit_password/:id' => 'writers#edit_password', as: 'edit_password'
  patch 'writers/update_password/:id' => 'writers#update_password', as: 'update_password'
end

app/views/layouts/_header.html.erb
<% if writer_signed_in? %>
  <nav class="header_nav">
    <ul>
      <li>
        <%= link_to root_path, data: { 'turbolinks' => false } do %>
          <h2 class="header_title">MY BLOG</h2>
        <% end %>
      </li>
      <li>
      	<%= link_to new_article_path do %>
          <div class="new"></div>
        <% end %>
      </li>
      <li>
      	<%= link_to root_path, data: { 'turbolinks' => false } do %>
          <div class="index_header"></div>
        <% end %>
      </li>
      <li>
      	<%= link_to writer_path(current_writer) do %>
          <div class="myPage"></div>
        <% end %>
      </li>
   	  <li class="navbar-right">
        <%= link_to destroy_writer_session_path, method: :delete do %>
          <div class="logout"></div>
        <% end %>
   	  </li>
    </ul>
  </nav>
<% else %>
  <nav class="header_nav">
    <ul>
      <li>
        <%= link_to root_path, data: { 'turbolinks' => false } do %>
          <h2 class="header_title">MY BLOG</h2>
        <% end %>
      </li>
      <li>
        <%= link_to root_path, data: { 'turbolinks' => false } do %>
          <div class="index_header"></div>
        <% end %>
      </li>
      <li>
        <%= link_to about_path do %>
          <div class="myPage"></div>
        <% end %>
      </li>
    </ul>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>